version: '3'

services:
  pc-client-slim:
    image: php:7.4
    environment:
      docker: "true"
    ports:
      - 8080:8080
    command: "php -S 0.0.0.0:8080 -t /var/www/public"
    volumes:
      - .:/var/www
      - ./logs:/var/www/logs
