<?php
/**
 * @var \PartsCatalogsSlim\View\CarsView $view
 */
?>
<div class=" text-muted text-right">
    <?= $view->carsCount() ?> / <?= $view->carsTotal() ?>
</div>

<div class="shadow p-3 mt-2 bg-white rounded">
    <?php foreach ($view->filters() as $i => $filterView) { ?>

      <label for="" class="text-muted text-right">
        <small><?= $filterView->name() ?></small>
      </label>
      <div>

          <?php if ($filterView->isSelected()) { ?>

            <div class="btn-group btn-block" role="group">
              <div class="btn-group btn-block" role="group">
                <a id="btnGroupDrop<?= $i ?>" href="#" class="btn btn-light btn-block text-justify"
                   data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    <?= $filterView->value() ?>
                </a>
                <div class="dropdown-menu" aria-labelledby="btnGroupDrop<?= $i ?>">
                    <?php foreach ($filterView->values() as $value) { ?>

                        <?php if ($value->isSelected()) { ?>
                        <a class="dropdown-item active"
                           href="<?= $view->generateUrlForSelect($value) ?>"><?= $value ?></a>
                        <?php } else { ?>
                        <a class="dropdown-item disabled" href="#"><?= $value ?></a>
                        <?php } ?>


                    <?php } ?>
                </div>
              </div>
              <a class="btn btn-secondary btn-light text-danger" href="<?= $view->generateUrlForReset($filterView) ?>">
                <i class="fa fa-times"></i>
              </a>
            </div>

          <?php } else { ?>

            <div class="dropdown btn-block">
              <a class="btn btn-light btn-block text-justify" href="#" role="button" id="btnGroupDrop<?= $i ?>"
                 data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <?= $filterView->value() ?>
              </a>

              <div class="dropdown-menu" aria-labelledby="btnGroupDrop<?= $i ?>">

                  <?php foreach ($filterView->values() as $fsElementValue) { ?>

                      <?php if ($fsElementValue->isAvailable()) { ?>
                      <a class="dropdown-item" href="<?= $view->generateUrlForSelect($fsElementValue) ?>"><?= $fsElementValue ?></a>
                      <?php } ?>

                  <?php } ?>
                  <?php if ($filterView->hasUnAvailableValues()) { ?>
                    <div class="dropdown-divider"></div>
                      <?php foreach ($filterView->values() as $fsElementValue) { ?>

                          <?php if (!$fsElementValue->isAvailable()) { ?>
                        <a class="dropdown-item disabled" href="#"><?= $fsElementValue ?></a>
                          <?php } ?>

                      <?php } ?>
                  <?php } ?>
              </div>
            </div>

          <?php } ?>


      </div>
    <?php } ?>
</div>
