<?php
/** @var \PartsCatalogsSlim\View\LayoutView $view */
?>
<!doctype html>
<html lang="en">
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

  <!-- Font Awesome CSS -->
  <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

  <title><?= $view->title() ?></title>
  <style>

    ol.catalogs li + li:before {
      content: "/";
      color: #ccc;
      padding-left: 5px;
    }

    @media (min-width: 576px) {
      .cc-sm-1 {
        column-count: 1;
      }
    }

    @media (min-width: 768px) {
      .cc-md-1 {
        column-count: 1;
      }

      .cc-md-2 {
        column-count: 2;
      }

      .cc-md-3 {
        column-count: 3;
      }

    }

    @media (min-width: 992px) {
      .cc-lg-1 {
        column-count: 1;
      }

      .cc-lg-2 {
        column-count: 2;
      }

      .cc-lg-3 {
        column-count: 3;
      }
    }

    @media (min-width: 1140px) {
      .cc-xs-3 {
        column-count: 3;
      }
    }

    .group-img-bg {
      background-repeat: no-repeat;
      background-position: bottom right;
      background-size: contain, contain;
      max-height: 300px;
      overflow: hidden;
    }

    .part-pos {
      background-color: rgba(0, 0, 0, 0.15);
      border-radius: 6px;
      position: absolute;
    }

    .part-pos:hover {
      border: 1px solid #007bff;
    }
    .part-pos {
        transform: scale(1.7)
    }
    @keyframes crescendo {
        0%   {transform: scale(2.5);}
        100% {transform: scale(1.7);}
    }
    @media (min-width: 576px) {
        .part-pos {
            transform: scale(1.4)
        }
    }
    @media (min-width: 768px) {
        .part-pos {
            transform: scale(1)
        }
        @keyframes crescendo {
            0%   {transform: scale(1.7);}
            100% {transform: scale(1);}
        }
    }
    .table-pos.target > div,
    .table-pos:target > div {
        border-left-style: solid;
        border-left-width: 4px;
        border-left-color: #ffc107 !important;
    }
    .table-pos:target > .badge {
        background-color: #ffc107 !important;
    }

    .scheme-pos.target .part-pos,
    .scheme-pos:target .part-pos {
        background-color: rgba(255, 193, 7, 0.5);
        animation: crescendo .6s alternate ease-in;
    }


    .car-row:hover {
        z-index: 1;
        background-color: rgb(248, 249, 250);
    }
  </style>
</head>
<body>

<nav class="navbar navbar-light bg-light shadow bg-white rounded navbar-expand">
  <a class="navbar-brand text-primary" href="/">PC</a>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">

    <ul class="navbar-nav mr-auto"></ul>
    <ul class="navbar-nav">
      <li class="nav-item dropdown">

            <a class="btn btn-link text-muted" href="/vin/">Search by VIN
              <i class="fa fa-search ml-2"></i>
            </a>

      </li>
    </ul>
  </div>
</nav>

<div class="container-fluid p-4">
    <?= $content ?>
</div>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

</body>
</html>